#!/usr/bin/python3

# SPDX-FileCopyrightText: 2024 Junya Wada
# SPDX-License-Identifier: GPL-3.0-only

def main():
    text = input()
    
    for c in text:
        if c.isalpha():
            c = c.lower()
            if c == 'a': print('・ー', end='')
            elif c == 'b': print('ー・・・', end='')
            elif c == 'c': print('ー・ー・', end='')
            elif c == 'd': print('ー・・', end='')
            elif c == 'e': print('・', end='')
            elif c == 'f': print('・・ー・', end='')
            elif c == 'g': print('ーー・', end='')
            elif c == 'h': print('・・・・', end='')
            elif c == 'i': print('・・', end='')
            elif c == 'j': print('・ーーー', end='')
            elif c == 'k': print('ー・ー', end='')
            elif c == 'l': print('・ー・・', end='')
            elif c == 'm': print('ーー', end='')
            elif c == 'n': print('ー・', end='')
            elif c == 'o': print('ーーー', end='')
            elif c == 'p': print('・ーー・', end='')
            elif c == 'q': print('ーー・ー', end='')
            elif c == 'r': print('・ー・', end='')
            elif c == 's': print('・・・', end='')
            elif c == 't': print('ー', end='')
            elif c == 'u': print('・・ー', end='')
            elif c == 'v': print('・・・ー', end='')
            elif c == 'w': print('・ーー', end='')
            elif c == 'x': print('ー・・ー', end='')
            elif c == 'y': print('ー・ーー', end='')
            elif c == 'z': print('ーー・・', end='')
        
        elif c == '0': print('ーーーーー', end='')
        elif c == '1': print('・ーーーー', end='')
        elif c == '2': print('・・ーーー', end='')
        elif c == '3': print('・・・ーー', end='')
        elif c == '4': print('・・・・ー', end='')
        elif c == '5': print('・・・・・', end='')
        elif c == '6': print('ー・・・・', end='')
        elif c == '7': print('ーー・・・', end='')
        elif c == '8': print('ーーー・・', end='')
        elif c == '9': print('ーーーー・', end='')
        elif c == '.': print('・ー・ー・ー', end='')
        elif c == ',': print('ーー・・ーー', end='')
        elif c == '?': print('・・ーー・・', end='')
        elif c == '-': print('ー・・・・ー', end='')
        elif c == '/': print('ー・・ー・', end='')
        elif c == '@': print('・ーー・ー・', end='')
        

    print()

main()
