#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Junya Wada
# SPDX-License-Identifier: BSD-3-Clause

import sys

def tounm(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)
    
print(ans)
