#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryuichi Ueda <s23c1148re@s.chibakoudai.jp>

import sys

def tounm(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)
    
print(ans)
