#!/usr/bin/python3
import sys

def tounm(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)
    
print(ans)
